### ISSUE TITLE
Pokrywające się przyciski

### ISSUE THREAD

**Issue by smoczysko12** [Project-Trains/developer-kit-issues#10]
Po przeskalowaniu okna przycisk "Dodaj" pokrywa się z zakładkami.
![image](https://user-images.githubusercontent.com/73747060/110129830-adef3b80-7dc8-11eb-800d-7ac0909877a1.png)

**Comment by smoczysko12** [comment]
A tu się piętrowiec robi
![image](https://user-images.githubusercontent.com/73747060/110130975-f22f0b80-7dc9-11eb-8385-6976f40e4100.png)

**Comment by kalucky0** [comment]
Poprawka wyjdzie w wersji v0.1.2
