### ISSUE TITLE
Długi czas pojawianie się zdjęcia po przesłaniu

### ISSUE THREAD

**Issue by smoczysko12** [Project-Trains/developer-kit-issues#18]
Po przesłaniu zdjęcia trzeba czekać ok 2 min, aż zdjęcie się pojawi na liście. (Dla porównania dokumenty pojawiają się od razu.)

**Comment by kalucky0** [comment]
> Dla porównania dokumenty pojawiają się od razu.

Tyle że dokumenty i obrazki są przetwarzane przez dokładnie ten sam skrypt.

**Comment by kalucky0** [comment]
Jesteś pewien, że po prostu nie wszedłeś w złą zakładkę? U mnie zdjęcia pojawiają się natychmiast po dodaniu.
