### ISSUE TITLE
Błąd w zakładce zdjęcia

### ISSUE THREAD

**Issue by SZAKYPT** [Project-Trains/developer-kit-issues#7]
Po wejściu do zakładki zdjęcia jest napis ŁADOWANIE. Po co? skoro nic nie dodałem, zmieńmy ten napis po chwili np. na BRAK DODANYCH TREŚCI.

![błąd](https://user-images.githubusercontent.com/68403718/110092696-24c11000-7d9a-11eb-8016-d374d87ee9ae.png)

**Comment by kalucky0** [comment]
Jest napis "Ładowanie" dlatego, że musi załadować, że nic nie dodałeś, a jako iż back end nie został podłączony pod program, to nie ma czego załadować i robi to w nieskończoność.
